### ISSUE TITLE
Set up build system to generate spec preview link for main branch

### ISSUE THREAD

**Issue by s3ththompson** [w3c/aria-at-automation#27]
We need to set up a build system to run [bikeshed](https://github.com/tabatkins/bikeshed) after new PRs are merged so that we can maintain an up-to-date preview link for the repository.

Additionally, the repo is set up so that the main branch is `gh-pages`. We should change the main branch to `main` and have a separate action that commits the built spec to `gh-pages` for easy hosting and previewing.

**Comment by zcorpan** [comment]
Interim hack/workaround is to check in `index.html` to gh-pages manually.

**Comment by zcorpan** [comment]
Done.

The generated spec now available at https://w3c.github.io/aria-at-automation/ . I renamed the old `gh-pages` branch to `main` and created a new `gh-pages` so as to keep `main` clean.

`index.html` is still excluded by `.gitignore` so it needs a force add in `gh-pages`:

```
bikeshed
git add -f index.html
```

Leaving the issue open to make this automatic with CI.

FYI @mcking65

**Comment by zcorpan** [comment]
Fixed in #35.
